### ISSUE TITLE
faker 组件是干什么用的啊？

### ISSUE THREAD

**Issue by injy** [klsf/kldns#11]
如题。我看你引用了faker，做什么用的呢？

**Comment by klsf** [comment]
这个应该是laravel框架引用的，这个是用来生成测试数据的一个工具

**Comment by injy** [comment]
本来的程序也就2-3M吧，加上这个之后10几M了，而且也不用生成无用的测试数据吧，要不把这个删除掉吧。

然后现在好多人还用的php5.X  能不能搞一个对php要求低一点的版本啊？

**Comment by ghost** [comment]
laravel要求的php版本
